name: orio_tech_attendance_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  get: ^4.6.5
  fluttertoast: ^8.1.2
  get_storage: ^2.0.3
  connectivity_plus: ^3.0.2
  flutter_svg: ^2.0.0+1
  intl: ^0.18.0
  scrollable_positioned_list: ^0.3.2
  lottie: ^2.2.0
  dio: ^5.0.0
  platform_device_id: ^1.0.1
  permission_handler: ^10.2.0
  shimmer: ^2.0.0
  alt_sms_autofill: ^1.0.0
  easy_geofencing: ^0.2.0
  location: ^4.4.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/logos/
    - assets/images/

  fonts:
    - family: Ubuntu
      fonts:
        - asset: fonts/Ubuntu-Light.ttf
          weight: 300
        - asset: fonts/Ubuntu-LightItalic.ttf
          weight: 300
          style: italic
        - asset: fonts/Ubuntu-Regular.ttf
        - asset: fonts/Ubuntu-Italic.ttf
          style: italic
        - asset: fonts/Ubuntu-Medium.ttf
          weight: 500
        - asset: fonts/Ubuntu-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: fonts/Ubuntu-Bold.ttf
          weight: 500
        - asset: fonts/Ubuntu-BoldItalic.ttf
          weight: 500
          style: italic
